$script = "C:\Users\Administrator\.gemini\antigravity\skills\baoyu-image-gen\scripts\main.ts"
$outDir = "d:\vibe\skills-doc\ref-doc\slide-deck\se-week1"

$slides = @(
  @{ file="03-slide-programmer-pain.png"; prompt="16:9 landscape slide, sketch-notes hand-drawn style on warm off-white paper. Title '程序员的五大痛点' in bold Chinese handwritten marker. Subtitle '这些场景，你是否似曾相识？'. Five hand-drawn sticky notes scattered, each with warm gold background: 1) 上手就写后期填坑 2) 缺少方法论 3) 需求变更 4) 没有计划总是延期 5) 不懂协作. Center: stressed stick figure at desk with red exclamation marks. No slide numbers." },
  @{ file="04-slide-bezos-quote.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '十年后，什么不会变？' in bold Chinese handwritten marker. A large thought bubble with 'Jeff Bezos的洞察'. Below, three pillars: 数据结构与算法, 面向对象与设计模式, 软件工程 highlighted with gold underline. Foundation sketch. Warm tones. No slide numbers." },
  @{ file="05-slide-se-value.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '软件工程的三大价值' in bold Chinese handwritten. Subtitle '从无序到有序'. Three boxes stacked connected by arrows: 组织 with team icon in teal, 方法 with book in terracotta, 工具 with wrench in gold. Lightbulb at top. No slide numbers." },
  @{ file="06-slide-dao-shu-qi.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '道·术·器' bold Chinese handwritten. Subtitle '三维教学框架'. Large pyramid three layers: top 道Why sun icon gold, middle 术How compass terracotta, bottom 器What tools teal. Each layer description. No slide numbers." },
  @{ file="07-slide-course-modules.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '课程结构总览' bold Chinese handwritten. Subtitle '16周48课时四大模块'. Winding road bottom-left to top-right, four milestone flags: 模块一基础理论1-3周 book, 模块二项目过程4-11周 gear, 模块三案例前沿12-15周 rocket, 模块四综合实践16周 trophy. Warm tones. No slide numbers." },
  @{ file="08-slide-assessment.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '考核方式' bold Chinese handwritten. Subtitle '平时+团队项目+期末考试'. Hand-drawn pie chart: terracotta 20pct 平时成绩 checkmark, teal 50pct 团队项目 people, gold 30pct 期末考试 pen. Labels handwritten. No slide numbers." },
  @{ file="09-slide-reading-list.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '推荐参考书' bold Chinese handwritten. Four hand-drawn books on bookshelf: 软件工程实践者的研究方法 teal, 构建之法 terracotta, 人月神话 gold with star, 架构整洁之道 blue. Reading lamp. No slide numbers." },
  @{ file="10-slide-section-divider-1.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Large section divider: 第一讲 very bold Chinese handwritten centered. Banner below: 到底应该怎样理解软件工程？ Number 01 large light gold background. Gears and code brackets doodles. No slide numbers." },
  @{ file="11-slide-overwatch-case.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '守望先锋是怎么做出来的？' bold Chinese handwritten. Timeline four milestones: 2013立项 lightbulb, Demo 4英雄1地图 controller, 2014嘉年华 12英雄4地图 crowd, 2016.5正式发布 rocket. Dashed arrows. No slide numbers." },
  @{ file="12-slide-engineering-definition.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '什么是工程？' bold Chinese handwritten. Subtitle '有人参与有计划有步骤造产品'. Three icons: house 建筑工程, rocket 航天工程, laptop 软件工程. Bracket connecting to 工程. Four keywords gold highlight. No slide numbers." },
  @{ file="13-slide-software-crisis.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '软件危机：代价惨重的教训' bold Chinese handwritten. Left: cracked computer screen with error symbols warning triangles dollars in terracotta. Right: three bullets 软件质量低劣, 成本失控进度不可预测, 人员增加无法解决. Worried stick figure. No slide numbers." },
  @{ file="14-slide-os360.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title 'OS/360：1000人+5000人年=失败' bold Chinese handwritten. Subtitle '人月神话的由来'. Large numbers 1000人 5000人年 in terracotta. Tangled mess of lines. Book 人月神话 emerging. Dollar loss badge. No slide numbers." },
  @{ file="15-slide-therac25.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title 'Therac-25：程序Bug致人死亡' bold Chinese handwritten. Medical device with red warning. Radiation hazard sign. Large 100x in terracotta for overdose. Text 1985-1987 6起医疗事故. Memorial candle. No slide numbers." },
  @{ file="16-slide-se-birth.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '1968：软件工程的诞生' bold Chinese handwritten. Subtitle '北约会议50名顶尖专家'. Conference scene stick figures around table. Banner NATO 1968. Lightbulb above with Software Engineering. Warm vintage sepia feel. No slide numbers." },
  @{ file="17-slide-ieee-definition.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '软件工程的定义' bold Chinese handwritten. Subtitle 'IEEE 1993'. Scroll with quote 将系统化的规范的可度量的方法用于软件的开发运行和维护. Three badges: clock 按时完成, coin 成本可控, star 质量有保证. Bracket labeled 工程化. No slide numbers." },
  @{ file="18-slide-evolution.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '软件工程演化史' bold Chinese handwritten. Subtitle '从瀑布到AI半个世纪进化'. Winding river bottom to top with milestones: 1960s软件危机 warning, 1970s瀑布模型 waterfall, 1980s V模型螺旋 spiral, 1990s Scrum running, 2001敏捷 flame, 2010s云 cloud, 2020s AI robot. Colorful warm. No slide numbers." },
  @{ file="19-slide-core-formula.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Center: very large equation 软件工程=过程+方法+工具 in bold marker with gold underline. Below three boxes: circular arrow 过程:开发步骤, compass 方法:方法学, wrench 工具:提升效率. Bold impactful memorable. No slide numbers." },
  @{ file="20-slide-section-divider-2.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Large section divider 第二讲 very bold centered. Banner: 工程思维：把每件事都当作一个项目来推进. Number 02 large light gold background. Project checklist brain gears doodles. No slide numbers." },
  @{ file="21-slide-everything-project.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title 'Everything is a Project' bold handwritten. Subtitle '万事皆项目'. Large speech bubble with text. Around it sketch icons: homework notebook, rocket, birthday party, software app, travel plan. Connected by dashed arrows. Hub-spoke layout. No slide numbers." },
  @{ file="22-slide-six-stages.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '工程方法的六个阶段' bold Chinese handwritten. Subtitle '有目的有计划有步骤'. Six circles in flow: lightbulb想法, pencil概念, calendar计划, blueprint设计, hammer开发, rocket发布. Arrows connecting. Different accent colors. No slide numbers." },
  @{ file="23-slide-phone-case.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '案例：30分钟设计一部老年手机' bold Chinese handwritten. Split: LEFT chaotic group thought bubbles flying clock running out; RIGHT organized group plan on board checkmarks trophy. Clock center 30 minutes. No slide numbers." },
  @{ file="24-slide-phone-plan.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '获胜秘诀：把30分钟当作一个项目' bold Chinese handwritten. Gantt-chart timeline four colored blocks: blue 分析0-10min, green 设计11-15min, orange 开发16-25min, red 发布26-30min. Each with icon. Checkmark at end. No slide numbers." },
  @{ file="25-slide-local-vs-global.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '站在整体，而非局部' bold Chinese handwritten. LEFT magnifying glass showing tiny puzzle piece labeled 局部. RIGHT full assembled puzzle with pieces labeled 产品 开发 测试 运维. Arrow from glass to full puzzle labeled 整体. No slide numbers." },
  @{ file="26-slide-anti-patterns.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '局部思维的常见反模式' bold Chinese handwritten. Four cartoon panels 2x2 grid: 1) PM throwing wild ideas 需求天马行空 2) architect reinventing wheel 热衷造轮子 3) developer too many tech logos 追新技术 4) tester manual clicking 不学自动化. Each red X mark. No slide numbers." },
  @{ file="27-slide-global-thinking.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '站在项目整体的四个关注点' bold Chinese handwritten. Subtitle '质量进度成本用户'. Center compass with four quadrants: star质量, clock进度, coin成本, person用户. Four stick figures PM architect dev tester with green checkmarks pointing to center. No slide numbers." },
  @{ file="28-slide-engineering-mindset.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '什么是工程思维？' bold Chinese handwritten. Subtitle '一种思考问题的方式'. Center brain with gears inside. Three branches: 从项目角度看待问题, 用工程方法解决问题, 站在整体而非局部. Gold highlights. Banner '你不需要是项目经理'. No slide numbers." },
  @{ file="29-slide-exercise.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '课堂练习：把活动当项目' bold Chinese handwritten. Subtitle '用六阶段工程方法来规划'. Whiteboard with exercise: 场景你要组织一个50人参加的技术沙龙活动. Teacher pointing at board. Students in groups. Timer 5 min. Question marks exclamation marks. No slide numbers." },
  @{ file="30-slide-back-cover.png"; prompt="16:9 landscape slide, sketch-notes style on warm off-white paper. Title '本周要点回顾 and 下周预告' bold Chinese handwritten. Top: notebook page two formulas 软件工程=过程+方法+工具 and 工程思维=项目视角+工程方法+整体思维 with gold underlines. Bottom: arrow to 下周 with waterfall icon agile icon. Pencil doodle 课后思考. Warm encouraging. No slide numbers." }
)

$total = $slides.Count + 2
$i = 3
foreach ($s in $slides) {
    Write-Host "`n[$i/$total] Generating: $($s.file)..."
    $outPath = Join-Path $outDir $s.file
    & npx -y bun $script --prompt $s.prompt --image $outPath --provider openai --ar "16:9" 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  OK: $($s.file)"
    } else {
        Write-Host "  FAILED: $($s.file)"
    }
    $i++
}
Write-Host "`nAll done!"
